# Generated by Django 2.0.4 on 2018-08-16 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(blank=True, max_length=2048, null=True, verbose_name='script')),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='version')),
                ('remark', models.TextField(blank=True, max_length=2048, null=True, verbose_name='remark')),
                ('template', models.TextField(blank=True, max_length=2048, null=True, verbose_name='template')),
                ('is_available', models.BooleanField(default=1, verbose_name='is_available')),
                ('reference', models.CharField(blank=True, max_length=64, null=True, verbose_name='reference')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('data_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account_id', models.CharField(max_length=32, unique=True, verbose_name='account_id')),
                ('account_name', models.CharField(max_length=64, null=True, verbose_name='account_name')),
                ('account_login', models.CharField(max_length=32, null=True, verbose_name='account_login')),
                ('account_pin', models.CharField(max_length=32, null=True, verbose_name='account_pin')),
            ],
            options={
                'verbose_name_plural': 'account',
                'db_table': 'boss_account',
                'ordering': ['-account_id'],
                'verbose_name': 'account',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(blank=True, max_length=2048, null=True, verbose_name='script')),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='version')),
                ('remark', models.TextField(blank=True, max_length=2048, null=True, verbose_name='remark')),
                ('template', models.TextField(blank=True, max_length=2048, null=True, verbose_name='template')),
                ('is_available', models.BooleanField(default=1, verbose_name='is_available')),
                ('reference', models.CharField(blank=True, max_length=64, null=True, verbose_name='reference')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('data_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bill_number', models.CharField(max_length=32, unique=True, verbose_name='bill_number')),
                ('bill_memo', models.CharField(max_length=32, null=True, verbose_name='bill_memo')),
                ('biller', models.CharField(max_length=32, null=True, verbose_name='biller')),
                ('bill_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, null=True, verbose_name='bill_amount')),
                ('bill_due', models.DateField(null=True, verbose_name='bill_due')),
                ('bill_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account', verbose_name='bill_account')),
            ],
            options={
                'verbose_name_plural': 'bill',
                'db_table': 'boss_bill',
                'verbose_name': 'bill',
            },
        ),
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(blank=True, max_length=2048, null=True, verbose_name='script')),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='version')),
                ('remark', models.TextField(blank=True, max_length=2048, null=True, verbose_name='remark')),
                ('template', models.TextField(blank=True, max_length=2048, null=True, verbose_name='template')),
                ('is_available', models.BooleanField(default=1, verbose_name='is_available')),
                ('reference', models.CharField(blank=True, max_length=64, null=True, verbose_name='reference')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('data_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('rate_id', models.CharField(max_length=32, unique=True, verbose_name='rate_id')),
                ('rate_name', models.CharField(max_length=32, null=True, verbose_name='rate_name')),
                ('rate_per_project', models.IntegerField(default='0', null=True, verbose_name='rate_per_project')),
                ('rate_per_object', models.IntegerField(default='0', null=True, verbose_name='rate_per_object')),
                ('rate_cycle', models.CharField(choices=[('Y', '年'), ('M', '月'), ('W', '周'), ('d', '日')], max_length=32, null=True, verbose_name='rate_cycle')),
            ],
            options={
                'verbose_name_plural': 'service_rate',
                'db_table': 'boss_service_rate',
                'ordering': ['-rate_id'],
                'verbose_name': 'service_rate',
            },
        ),
    ]
