# Generated by Django 2.0.4 on 2018-08-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(blank=True, max_length=2048, null=True, verbose_name='script')),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='version')),
                ('remark', models.TextField(blank=True, max_length=2048, null=True, verbose_name='remark')),
                ('template', models.TextField(blank=True, max_length=2048, null=True, verbose_name='template')),
                ('is_available', models.BooleanField(default=1, verbose_name='is_available')),
                ('reference', models.CharField(blank=True, max_length=64, null=True, verbose_name='reference')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('data_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('object_id', models.CharField(max_length=32, unique=True, verbose_name='object_id')),
                ('object_reference_id', models.CharField(max_length=32, null=True, verbose_name='object_reference_id')),
                ('object_name', models.CharField(max_length=32, null=True, verbose_name='object_name')),
                ('object_model', models.CharField(max_length=32, null=True, verbose_name='object_model')),
            ],
            options={
                'verbose_name_plural': 'object',
                'db_table': 'boss_object',
                'ordering': ['-object_id'],
                'verbose_name': 'object',
            },
        ),
        migrations.CreateModel(
            name='ObjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(blank=True, max_length=2048, null=True, verbose_name='script')),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='version')),
                ('remark', models.TextField(blank=True, max_length=2048, null=True, verbose_name='remark')),
                ('template', models.TextField(blank=True, max_length=2048, null=True, verbose_name='template')),
                ('is_available', models.BooleanField(default=1, verbose_name='is_available')),
                ('reference', models.CharField(blank=True, max_length=64, null=True, verbose_name='reference')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('data_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('obj_group_id', models.CharField(max_length=32, unique=True, verbose_name='obj_group_id')),
                ('obj_group_name', models.CharField(max_length=32, null=True, verbose_name='obj_group_name')),
                ('object_category', models.CharField(choices=[('C', 'compressor'), ('B', 'boiler'), ('E', 'engline'), ('G', 'generator')], max_length=32, null=True, verbose_name='object_category')),
            ],
            options={
                'verbose_name_plural': 'object_group',
                'db_table': 'boss_object_group',
                'ordering': ['-obj_group_id'],
                'verbose_name': 'object_group',
            },
        ),
    ]
