# Generated by Django 2.0.4 on 2018-08-16 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('object', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='objectgroup',
            name='obj_group_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='object',
            name='obj_group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='object.ObjectGroup', verbose_name='obj_group_id'),
        ),
        migrations.AddField(
            model_name='object',
            name='object_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
