# Generated by Django 2.0.4 on 2018-08-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(blank=True, max_length=2048, null=True, verbose_name='script')),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='version')),
                ('remark', models.TextField(blank=True, max_length=2048, null=True, verbose_name='remark')),
                ('template', models.TextField(blank=True, max_length=2048, null=True, verbose_name='template')),
                ('is_available', models.BooleanField(default=1, verbose_name='is_available')),
                ('reference', models.CharField(blank=True, max_length=64, null=True, verbose_name='reference')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('data_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('calculate_data_id', models.CharField(max_length=16, unique=True, verbose_name='calculate_data_id')),
                ('calculate_data_name', models.CharField(max_length=16, null=True, verbose_name='calculate_data_name')),
                ('project_id', models.CharField(max_length=16, null=True, verbose_name='project_id')),
                ('data', models.TextField(blank=True, null=True, verbose_name='data')),
            ],
            options={
                'verbose_name_plural': 'calculate_data',
                'db_table': 'boss_calculate_data',
                'ordering': ['-calculate_data_id'],
                'verbose_name': 'calculate_data',
            },
        ),
        migrations.CreateModel(
            name='FormatData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(blank=True, max_length=2048, null=True, verbose_name='script')),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='version')),
                ('remark', models.TextField(blank=True, max_length=2048, null=True, verbose_name='remark')),
                ('template', models.TextField(blank=True, max_length=2048, null=True, verbose_name='template')),
                ('is_available', models.BooleanField(default=1, verbose_name='is_available')),
                ('reference', models.CharField(blank=True, max_length=64, null=True, verbose_name='reference')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('data_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('format_data_id', models.CharField(max_length=16, unique=True, verbose_name='format_data_id')),
                ('format_data_name', models.CharField(max_length=16, null=True, verbose_name='format_data_name')),
                ('project_id', models.CharField(max_length=16, null=True, verbose_name='project_id')),
                ('data', models.TextField(blank=True, null=True, verbose_name='data')),
            ],
            options={
                'verbose_name_plural': 'format_data',
                'db_table': 'boss_format_data',
                'ordering': ['-format_data_id'],
                'verbose_name': 'format_data',
            },
        ),
        migrations.CreateModel(
            name='OriginalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(blank=True, max_length=2048, null=True, verbose_name='script')),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='version')),
                ('remark', models.TextField(blank=True, max_length=2048, null=True, verbose_name='remark')),
                ('template', models.TextField(blank=True, max_length=2048, null=True, verbose_name='template')),
                ('is_available', models.BooleanField(default=1, verbose_name='is_available')),
                ('reference', models.CharField(blank=True, max_length=64, null=True, verbose_name='reference')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('data_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('original_data_id', models.CharField(max_length=16, unique=True, verbose_name='original_data_id')),
                ('original_data_name', models.CharField(max_length=16, null=True, verbose_name='original_data_name')),
                ('project_id', models.CharField(max_length=16, null=True, verbose_name='project_id')),
                ('data', models.TextField(blank=True, null=True, verbose_name='data')),
            ],
            options={
                'verbose_name_plural': 'original_data',
                'db_table': 'boss_original_data',
                'ordering': ['-original_data_id'],
                'verbose_name': 'original_data',
            },
        ),
    ]
