# Generated by Django 2.0.4 on 2018-08-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(blank=True, max_length=2048, null=True, verbose_name='script')),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='version')),
                ('remark', models.TextField(blank=True, max_length=2048, null=True, verbose_name='remark')),
                ('template', models.TextField(blank=True, max_length=2048, null=True, verbose_name='template')),
                ('is_available', models.BooleanField(default=1, verbose_name='is_available')),
                ('reference', models.CharField(blank=True, max_length=64, null=True, verbose_name='reference')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('data_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('program_id', models.CharField(max_length=16, null=True, unique=True, verbose_name='program_id')),
                ('program_name', models.CharField(max_length=24, null=True, unique=True, verbose_name='program_name')),
                ('program_type', models.CharField(choices=[('filter', '过滤器'), ('organizer', '组织器')], max_length=24, null=True, verbose_name='program_type')),
            ],
            options={
                'verbose_name_plural': 'program',
                'db_table': 'boss_program',
                'ordering': ['-program_id'],
                'verbose_name': 'program',
            },
        ),
    ]
