# Generated by Django 2.0.4 on 2018-08-16 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(blank=True, max_length=2048, null=True, verbose_name='script')),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='version')),
                ('remark', models.TextField(blank=True, max_length=2048, null=True, verbose_name='remark')),
                ('template', models.TextField(blank=True, max_length=2048, null=True, verbose_name='template')),
                ('is_available', models.BooleanField(default=1, verbose_name='is_available')),
                ('reference', models.CharField(blank=True, max_length=64, null=True, verbose_name='reference')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('data_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dashboard_id', models.CharField(max_length=32, unique=True, verbose_name='dashboard_id')),
                ('dashboard_url', models.CharField(max_length=256, null=True, verbose_name='dashboard_url')),
                ('dashboard_project', models.CharField(blank=True, max_length=32, null=True, verbose_name='dashboard_project')),
                ('dashboard_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account', verbose_name='dashboard_account')),
            ],
            options={
                'verbose_name_plural': 'dashboard',
                'db_table': 'boss_dashboard',
                'ordering': ['-dashboard_id'],
                'verbose_name': 'dashboard',
            },
        ),
    ]
