# Generated by Django 2.0.4 on 2018-08-16 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preprocess', '0001_initial'),
        ('output', '0001_initial'),
        ('object', '0001_initial'),
        ('message', '0001_initial'),
        ('account', '0001_initial'),
        ('parameter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(blank=True, max_length=2048, null=True, verbose_name='script')),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='version')),
                ('remark', models.TextField(blank=True, max_length=2048, null=True, verbose_name='remark')),
                ('template', models.TextField(blank=True, max_length=2048, null=True, verbose_name='template')),
                ('is_available', models.BooleanField(default=1, verbose_name='is_available')),
                ('reference', models.CharField(blank=True, max_length=64, null=True, verbose_name='reference')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('data_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project_id', models.CharField(max_length=32, unique=True, verbose_name='project_id')),
                ('project_name', models.CharField(max_length=32, null=True, verbose_name='project_name')),
                ('project_start_from', models.DateField(null=True, verbose_name='project_start_from')),
                ('project_end_by', models.DateField(null=True, verbose_name='project_end_by')),
                ('enable_time', models.DateTimeField(null=True, verbose_name='date_created')),
                ('object_id', models.IntegerField(null=True, verbose_name='object_id')),
                ('project_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account', verbose_name='project_account')),
                ('project_ana_para', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parameter.AnalysisParameter', verbose_name='project_ana_para')),
                ('project_dashboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='output.Dashboard', verbose_name='project_dashboard')),
                ('project_filter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preprocess.DataFilter', verbose_name='project_filter')),
                ('project_msg_out', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='message.MessageOut', verbose_name='project_msg_out')),
                ('project_obj_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='object.ObjectGroup', verbose_name='project_obj_group')),
                ('project_opt_para', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parameter.OptimizationParameter', verbose_name='project_opt_para')),
                ('project_organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preprocess.DataOrganizer', verbose_name='project_organizer')),
            ],
            options={
                'verbose_name_plural': 'analytic_project',
                'db_table': 'boss_analytic_project',
                'ordering': ['-project_id'],
                'verbose_name': 'analytic_project',
            },
        ),
    ]
