# Generated by Django 2.0.4 on 2018-08-16 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source', '0001_initial'),
        ('account', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticproject',
            name='project_pipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='source.DataPipe', verbose_name='project_pipe'),
        ),
        migrations.AddField(
            model_name='analyticproject',
            name='project_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.ServiceRate', verbose_name='project_rate'),
        ),
        migrations.AddField(
            model_name='analyticproject',
            name='project_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='source.DataSource', verbose_name='project_source'),
        ),
    ]
