# Generated by Django 2.0.4 on 2018-08-23 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_account_user'),
        ('project', '0003_analyticproject_project_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountToProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(blank=True, max_length=2048, null=True, verbose_name='script')),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='version')),
                ('remark', models.TextField(blank=True, max_length=2048, null=True, verbose_name='remark')),
                ('template', models.TextField(blank=True, max_length=2048, null=True, verbose_name='template')),
                ('is_available', models.BooleanField(default=1, verbose_name='is_available')),
                ('reference', models.CharField(blank=True, max_length=64, null=True, verbose_name='reference')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('data_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account', to_field='account_id')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.AnalyticProject', to_field='project_id')),
            ],
            options={
                'db_table': 'account_to_project',
            },
        ),
        migrations.AlterUniqueTogether(
            name='accounttoproject',
            unique_together={('account_id', 'project_id')},
        ),
    ]
