# Generated by Django 2.0.4 on 2018-08-16 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(blank=True, max_length=2048, null=True, verbose_name='script')),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='version')),
                ('remark', models.TextField(blank=True, max_length=2048, null=True, verbose_name='remark')),
                ('template', models.TextField(blank=True, max_length=2048, null=True, verbose_name='template')),
                ('is_available', models.BooleanField(default=1, verbose_name='is_available')),
                ('reference', models.CharField(blank=True, max_length=64, null=True, verbose_name='reference')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('data_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ana_para_id', models.CharField(max_length=16, unique=True, verbose_name='ana_para_id')),
                ('ana_para_name', models.CharField(max_length=24, unique=True, verbose_name='ana_para_name')),
            ],
            options={
                'verbose_name_plural': 'analysis_parameter',
                'db_table': 'boss_analysis_parameter',
                'ordering': ['-ana_para_id'],
                'verbose_name': 'analysis_parameter',
            },
        ),
        migrations.CreateModel(
            name='OptimizationParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(blank=True, max_length=2048, null=True, verbose_name='script')),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='version')),
                ('remark', models.TextField(blank=True, max_length=2048, null=True, verbose_name='remark')),
                ('template', models.TextField(blank=True, max_length=2048, null=True, verbose_name='template')),
                ('is_available', models.BooleanField(default=1, verbose_name='is_available')),
                ('reference', models.CharField(blank=True, max_length=64, null=True, verbose_name='reference')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('data_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('opt_para_id', models.CharField(max_length=16, unique=True, verbose_name='opt_para_id')),
                ('opt_para_name', models.CharField(max_length=24, unique=True, verbose_name='opt_para_name')),
                ('object_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='object.Object', verbose_name='object_id')),
            ],
            options={
                'verbose_name_plural': 'optimization_parameter',
                'db_table': 'boss_optimization_parameter',
                'ordering': ['-opt_para_id'],
                'verbose_name': 'optimization_parameter',
            },
        ),
    ]
